export const DISTRICT_OPTIONS = [
  { value: 'bo', label: 'Bo District' },
  { value: 'bombali', label: 'Bombali District' },
  { value: 'bonthe', label: 'Bonthe District' },
  { value: 'falaba', label: 'Falaba District' },
  { value: 'kailahun', label: 'Kailahun District' },
  { value: 'kambia', label: 'Kambia District' },
  { value: 'karene', label: 'Karene District' },
  { value: 'kenema', label: 'Kenema District' },
  { value: 'koinadugu', label: 'Koinadugu District' },
  { value: 'kono', label: 'Kono District' },
  { value: 'moyamba', label: 'Moyamba District' },
  { value: 'port-loko', label: 'Port Loko District' },
  { value: 'pujehun', label: 'Pujehun District' },
  { value: 'tonkolili', label: 'Tonkolili District' },
  { value: 'western-urban', label: 'Western Area Urban' },
  { value: 'western-rural', label: 'Western Area Rural' },
  { value: 'custom', label: 'Other / Custom District' },
];

export const DISTRICT_CHIEFDOMS = {
  bo: ['Badjia', 'Bagbo', 'Bagbwe', 'Baoma', 'Bumpe Gao', 'Gbo', 'Jaiama-Bongor', 'Kakua', 'Lugbu', 'Selenga', 'Valunia', 'Wonde'],
  bombali: [
    'Biriwa',
    'Bombali Shebora',
    'Bombali Sebora',
    'Gbendembu Ngowahun',
    'Libeisaygahun-Gbombahun',
    'Paki Masabong',
    'Safroko Limba',
    'Sanda Loko',
    'Sanda Tendaren',
    'Sella Limba',
    'Makari Gbanti',
  ],
  bonthe: ['Bum', 'Dema', 'Jong', 'Kpanda Kemo', 'Sittia', 'Imperi'],
  falaba: ['Dembelia Sinkunia', 'Folawira', 'Kasunko', 'Mongo', 'Neya', 'Wara Wara Bafodia', 'Wara Wara Yagala'],
  kailahun: ['Dea', 'Jawei', 'Kissi Kama', 'Kissi Teng', 'Kissi Tongi', 'Luwaa', 'Malema', 'Mandu', 'Njaiama Nimikoro', 'Peje Bongre', 'Peje West', 'Upper Bambara', 'Ward'],
  kambia: ['Bramaia', 'Gbinle Dixon', 'Magbema', 'Masungbala', 'Samu', 'Tonko Limba'],
  karene: ['Sanda Magbolonto', 'Sella Limba', 'Tambakha', 'Tonkoro', 'Samira Bendugu'],
  kenema: ['Dama', 'Dodo', 'Gorama Mende', 'Jaama Bongor', 'Kandu Leppiama', 'Koya', 'Lower Bambara', 'Malegohun', 'Niawa', 'Nomo', 'Simbaru', 'Small Bo', 'Tongo', 'Wandor'],
  koinadugu: ['Diang', 'Gbanti', 'Kabala', 'Nieni', 'Sengbeh', 'Sulima', 'Wara Wara Yagala', 'Wara Wara Bafodia', 'Kasunko'],
  kono: ['Gbane', 'Gbense', 'Kamara', 'Kataimbo', 'Lei', 'Nimiyama', 'Sandor', 'Soa', 'Tankoro', 'Toli', 'Yarddu'],
  moyamba: ['Bagruwa', 'Banta', 'Dasse', 'Fakunya', 'Kaiyamba', 'Kori', 'Kowa', 'Lower Banta', 'Ribbi', 'Timidale'],
  'port-loko': ['Buya Romende', 'Dibia', 'Kafu Bullom', 'Lokomasama', 'Maforki', 'Marampa', 'Masimera', 'Sanda Magbolonthor', 'Tinkatupa Makama'],
  pujehun: ['Barri', 'Gallinas', 'Kpaka', 'Makpele', 'Panga Krim', 'Soro-Gbema', 'Sowa', 'YKK'],
  tonkolili: ['Bombali Sebora', 'Kunike', 'Malal Mara', 'Sambaia Bendugu', 'Tane', 'Yoni', 'Kholifa', 'Kafe Simiria'],
  'western-urban': ['Central Freetown', 'East End', 'West End'],
  'western-rural': ['Freetown Peninsula', 'Koya', 'Rural Mountain', 'York'],
  'port-loko ': [],
};

export const FERTILIZER_OPTIONS = [
  'NPK 20-10-10',
  'NPK 15-15-15',
];
